### ISSUE TITLE
Add file IO class to load json as terminology

### ISSUE THREAD

**Issue by cpinter** [QIICR/QuantitativeReporting#167] opened 2017-07-15 19:10 UTC

**Comment by lassoan** [comment] 2017-07-15 21:07
Use composite file extension (for example *.term.json) to make sure Slicer can guess correctly which IO class to use by default for these json files.

**Comment by fedorov** [comment] 2017-07-16 00:28
It would be best to check the `@schema` attribute value inside JSON to confirm the content type.

**Comment by lassoan** [comment] 2017-07-16 12:14
There is no inspection of file content during selection of default IO plugin. The decision is made based on the file name (the user can then override the selection). In general, file content is not enough to decide how to interpret the data (for example, a 3-component vector volume may be an RGB image or a grid transform).

Of course, the plugin will check the schema and reject the file if there is a mismatch.

If you use a simple .json extension the terminology IO plugin can still read the file, but if there are multiple IO plugins that can read .json files then the default IO plugin selection may not be correct.

**Comment by cpinter** [comment] 2017-07-16 22:03
I'm not sure if that's possible, but probably the best would be to support files with only .json extension (then the user needs to select Terminology in the drop-down menu), and when it's .term.json, then select that by default.

**Comment by lassoan** [comment] 2017-07-16 22:18
This consistent file naming is required if you want to maintain optimal user experience. There will be several other data structures that will be saved as .json and you don't want the user to choose each time how to interpret that data. We learned this from our own earlier mistakes with nrrd (volume/transform/sequence) and csv files (tables/fiducials/annotations). 

It is a very little effort now to add add .json and .term.json (or something similar) as recognized extensions in the IO plugin. Somewhat more effort (but should not be too difficult) is to use .term.json for all new terminology related json files and gradually rename all existing files (e.g., at the next major version update).

**Comment by cpinter** [comment] 2017-07-16 22:24
I think this is exactly what I suggested, that we recognize both.

I suggested that we keep the json only extension because I don't think it's realistic to expect users to name all the custom terminology files *.term.json. This is also something that we know based on earlier experience :)

**Comment by lassoan** [comment] 2017-07-16 22:25
> I'm not sure if that's possible

It's all already implemented in the Slicer core. Slicer will choose that plugin by default, which has the most specific composite extension.

Example:

Two IO plugins are registered that accepts .json files:
* TerminologyIOPlugin: .json, .term.json
* CLIParameterIOPlugin: .json, .cli.json

Drag-and-drop a file:
* something.json file => default IO plugin will be non-deterministic (the first one that was registered or something similar), user may select another
* something.term.json file => TerminologyIOPlugin will be selected by default
* something.cli.json file => CLIParameterIOPlugin will be selected by default

**Comment by lassoan** [comment] 2017-07-16 22:27
> I don't think it's realistic to expect users to name all the custom terminology files *.term.json

When all the official files are named like this and the storage node will use this composite extension by default then the users will have very little motivation to rename the files.

**Comment by cpinter** [comment] 2017-07-16 22:28
Will do that

**Comment by cpinter** [comment] 2017-07-17 00:38
Another change that I'm bumping into just now.
The schema files were moved from https://raw.githubusercontent.com/qiicr/dcmqi/master/doc to https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/schemas. Is it then expected to have these as schema values in the files as well?
As far as I see the sample context files have not been changed on GitHub, maybe it was an oversight?
https://github.com/QIICR/dcmqi/blob/master/doc/segContexts/SegmentationCategoryTypeModifier-DICOM-Master.json

**Comment by cpinter** [comment] 2017-07-17 01:04
What I did:
* Changed the schema information in the files in the Slicer repo
* Allow loading terminologies using both the old and the new schema link (so that files that worked before still work)
I committed the changes now, let me know if I should change something
https://github.com/Slicer/Slicer/commit/e7bd6b86c5c38e380bbc6e6a4f2e306503042637

**Comment by lassoan** [comment] 2017-07-17 02:12
I had a look at the schema filenames at https://github.com/QIICR/dcmqi/tree/master/doc/schemas and noticed that you already use the -schema.json prefix for all your schema files, so it is almost good.

anatomic-context-schema.json 
common-schema.json 
pm-context-schema.json 
pm-schema.json 
seg-schema.json 
segment-context-common-schema.json 
segment-context-schema.json 
sr-common-schema.json 
sr-tid1500-schema.json

There are just two issues with the current filenames:

1. The '-' character is not a reliable separator for composite file extension. Users may think that it is part of the filename and may accidentally modify it (anatomic-context-schema-2.json) and implementing parsing with either - or . character would be complex and not very robust.

2. .schema.json may not be specific enough. We may want to store other schema files in json in the future. It would be better to indicate that it is a dcmqi schema.

@fedorov what do you think about these file names?

Instead of anatomic-context-schema.json ->

- anatomic-context.schema.dcmqi.json
- anatomic-context.dcmqi.schema.json
- anatomic-context.qi.schema.json
- anatomic-context.schema.qi.json
- anatomic-context.qischema.json
- anatomic-context.term.schema.json
- anatomic-context.schema.term.json
- anatomic-context.dcmqi.json

**Comment by cpinter** [comment] 2017-07-17 13:10
If we change them, then we should do it fast, because then we can replace the second schema url with the new one instead of adding a third.

**Comment by lassoan** [comment] 2017-07-17 14:20
Yes, I fully agree. I'm trying to get a decision made on the naming quickly, because the later it is done, the more painful the change will be.

**Comment by fedorov** [comment] 2017-07-17 14:43
Just to clarify, the only reason these dotted names are considered is because we cannot inspect the content of the json file in Slicer for the `@schema` attribute?

**Comment by fedorov** [comment] 2017-07-17 14:46
I personally don't like these dotted names. In a sense you are establishing a new convention, at worst known only to you, and at best only to the Slicer developers. The standard way to define content of a json file is to reference a schema. I do not see why dcmqi file names should be structured this way to work around a limitation of Slicer. I believe dot is there to separate file name from the extension, and adding more dots only increases confusion.

**Comment by cpinter** [comment] 2017-07-17 15:02
I'm OK with either changing or not changing the schema file names.
However their path was changed once, so I had to make changes in Slicer core. @fedorov do you agree with the changes that I described above? https://github.com/QIICR/QuantitativeReporting/issues/167#issuecomment-315651364

**Comment by lassoan** [comment] 2017-07-17 15:09
> new convention, at worst known only to you

It is widely used in cases when inspecting a file content is not feasible or desirable, think about .tar.gz, tar.bz2.

> The standard way to define content of a json file is to reference a schema.

Of course, and that will remain so. The file extension is important to figure out how to interpret isolated files, when you don't have a context, have no idea about the origin, intent, format, and what kind of information it may contain. Once you have a general idea, of course the content will be analyzed accordingly. Useful for filtering (file name pattern matching), batch processing, opening in applications that know the specific composite file extension.

The nice thing is that existing software that are associated with .json files will still reocognize and work well. You've already realized the need for adding the schema postfix to all your files, I would just suggest to formalize this and make this a bit easier to detect.

This is not a new issue. We went through several potential solutions for different file formats and so far composite file extensions seems to be the best solution (-stat.nrrd is not robust enough; .fcsv is not recognized by software that can read/edit .csv files; .tar.gz is a very widely used convention). You not only help Slicer but your own users and other software developers if you actually formalize this convention; instead of just happen to have all your files ending with -schema.json.

@fedorov It's completely up to you how you decide, I just wanted to make it clear that you are running into a situation that is easy to handle now but may be much more difficult to manage in the future.

**Comment by fedorov** [comment] 2017-07-17 15:38
@lassoan I understand the idea, but it's a hard sell generalizing the convention used by widely popular tools such as examples you provided. In the end, you cannot expect that your users will find, read, understand and follow precisely the documentation that would instruct them how to name their json file, so you would need to inspect anyway to be user-friendly. Even ITK image file readers have the capability to do basic inspection. .json should be sufficient to specify the general class of readers to do inspection. My basic argument is not to introduce yet another convention or "standard".

**Comment by lassoan** [comment] 2017-07-17 16:56
ITK is one of the examples that demonstrates that simply inspecting file contents is not always enough. The problem is that the file content is often ambiguous: for a volume of 3-component scalars it is not clear if it is a 3-time-point time sequence, an RGB volume, a displacement field, or a grid transform. But this is probably a limitation of the file formats that ITK has to deal with.

Using a carefully designed schema structure, maybe with inheritance, etc. can probably fully specify the file content accurately and in a way that less-specialized components may interpret it as well. However, to get this information, you have to parse the file, check if the schema matches that you can interpret (you may need to read the schema file as well, maybe even retrieve the schema file from the network). While this is certainly possible to implement, compare this effort to having a look at the file name. The same way as for users it is a convenience to that you can get a good idea about what's inside, it's a convenience for software, too.

You don't have to make it a hard requirement, it may be just a recommendation, a practice that you follow consistently. Very similarly how you have your convention established already.

**Comment by pieper** [comment] 2017-07-17 17:21
I agree with Andras on this.

**Comment by fedorov** [comment] 2017-07-17 18:11
> While this is certainly possible to implement, compare this effort to having a look at the file name. 

It is not bulletproof, obviously. What I mean is that looking at the file name that contains "extensions hints" is at least as reliable as looking at the `@schema` attribute of the json content. The difference is that this attribute is already standardized. Your example for the 3-component scalar vs RGB illustrates a situation that cannot be addressed with the capabilities of the format, but the issue at hand is different.

Having said that, considering that this change will make so many people happy, and should (in theory) not break anything, I am fine with the change after all. You didn't convince me, but I may still be wrong. Feel free to make a PR, or file an issue on dcmqi. My only worry about compatibility is whether these multiple dots will cause confusion for any existing application. There are at least some posts suggesting that using multiple dots in the file name may not be a good idea in practice:
* https://superuser.com/questions/450603/should-file-names-contain-multiple-periods
* https://windowssecrets.com/forums/showthread.php/176180-Using-multiple-periods-in-file-names

And with some operating systems hiding file extension (file extension being defined as the part after the last dot), result can indeed lead to more confusion.

**Comment by lassoan** [comment] 2017-07-18 04:24
Thanks Andrey. I don't anticipate that using composite extensions will cause complications (we've been using those for a while without any problems) and it'll make things simpler.

**Comment by cpinter** [comment] 2017-07-18 12:46
Thanks Andrey!

I'd like to ask you and @che85 to please notify us in the future if any files participating in the standard changes or moves, because for example the moving of the scema files to a different folder in the repo did break the validation function, but probably nobody noticed. I corrected the above issue as described above.

Also please review the chages and close the issue or let me know otherwise if I need to fix anything. Thanks!

**Comment by fedorov** [comment] 2017-07-18 22:53
@cpinter I don't have any other concerns about the PR, but I haven't got around to update the names in the dcmqi repository. Feel free to close the issue as soon as the PR is merged!

**Closed** 2017-07-20 19:17 UTC
