### ISSUE TITLE
tid1500 plugin loading error

### ISSUE THREAD

**Issue by pieper** [QIICR/QuantitativeReporting#243] opened 2019-07-13 15:31 UTC
Testing #240 with QR extension build from today on nightly.

* loaded CT dicom and got error dialog about TID1500
* images loaded normally but error below was in. log

```
Traceback (most recent call last):
  File "/private/tmp/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 730, in getLoadablesFromFileLists
    loadablesByPlugin[plugin] = plugin.examineForImport(fileLists)
  File "/private/tmp/Slicer.app/Contents/Extensions-28388/QuantitativeReporting/lib/Slicer-4.11/qt-scripted-modules/base/DICOMPluginBase.py", line 53, in examineForImport
    loadablesForFiles = self.examineFiles(files)
  File "/private/tmp/Slicer.app/Contents/Extensions-28388/QuantitativeReporting/lib/Slicer-4.11/qt-scripted-modules/DICOMTID1500Plugin.py", line 32, in examineFiles
    uid = self.getDICOMValue(dataset, "SOPInstanceUID")
  File "/private/tmp/Slicer.app/Contents/Extensions-28388/SlicerDevelopmentToolbox/lib/Slicer-4.11/qt-scripted-modules/SlicerDevelopmentToolboxUtils/decorators.py", line 194, in __call__
    raise TypeError("no match for types %s" % str(types))
TypeError: no match for types ('FileDataset', 'str')
Warning: Plugin failed: DICOMTID1500Plugin

See python console for error message.
```

**Comment by fedorov** [comment] 2019-07-15 03:26
I cannot reproduce this error. I tried, and could load a CT image with the TID1500 plugin enabled, and without any errors in the log.

Can you share the dataset, or give more details on the steps to reproduce?

**Comment by pieper** [comment] 2019-07-15 14:01
As with #240 this happens on the nightly.

**Comment by fedorov** [comment] 2019-07-17 16:35
Should be fixed in https://github.com/QIICR/SlicerDevelopmentToolbox/commit/407d02f5e2e4e7802f60df75e249c75e55a674e7

**Closed by fedorov** 2019-07-17 16:35 UTC

**Comment by pieper** [comment] 2019-07-18 14:10
Fixed - thank you!
