### ISSUE TITLE
Auto discovery of terminology json files in Slicer

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#141] opened 2017-02-18 22:15 UTC
@cpinter I am adding this issue here, so it is easier to track progress.

**Comment by fedorov** [comment] 2017-02-23 21:08
Could add the additional JSON files to the NA-MIC settings folder (need to confirm this folder can be accessed in a general fashion)

**Comment by cpinter** [comment] 2017-02-23 21:57
I was able to bedug. The problem is that by the time the module exit function is called, the views are already dstroyed, and when trying to remove actors, it crashes. I find it strange that restart and simple exit works differently. I'll try to do a check before removing those actors using the layout manager.

**Comment by cpinter** [comment] 2017-03-01 20:27
Committed in
https://github.com/Slicer/Slicer/commit/48a32d6a3e7524533d9f196064dc909887ab0998
I'm testing on Mac now

**Comment by cpinter** [comment] 2017-03-02 15:03
Works on Mac too.

**Comment by fedorov** [comment] 2017-03-08 13:36
Csaba, @chribaue tried to put this to work, and we identified a limitation that I missed earlier. In the current implementation, anatomic region context selection (and the corresponding JSON import by the user) is not exposed in the GUI and cannot be configured by the user. Can you add that feature? Should I summarize this in a separate issue?

**Comment by cpinter** [comment] 2017-03-08 13:55
Yes please, I think a separate issue would be helpful.
I assumed the anatomic region context does not need to be customized. Another wrong assumption...
Thanks

**Comment by fedorov** [comment] 2017-03-08 14:14
Sorry for not providing this instruction/feedback earlier. This is my fault. I will add an issue.

**Comment by chribaue** [comment] 2017-03-08 14:24
Thank you for your support guys! This would be really helpful.

**Closed** 2017-03-22 13:38 UTC
Labels: enhancement, SlicerTerminology
