### ISSUE TITLE
QuantitativeReporting breaks DICOM widget in Slicer 4.8

### ISSUE THREAD

**Issue by lassoan** [QIICR/QuantitativeReporting#203] opened 2017-11-20 15:57 UTC
When installing QuantitativeReporting extension for Slicer 4.8 (Windows) and switching to DICOM module, the browser does not appear.

```
[DEBUG][Qt] 20.11.2017 10:54:10 [] (unknown:0) - Session start time .......: 2017-11-20 10:54:10
[DEBUG][Qt] 20.11.2017 10:54:10 [] (unknown:0) - Slicer version ...........: 4.8.0 (revision 26489) win-amd64 - installed
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Operating system .........: Windows /  Professional /  (Build 9200) - 64-bit
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Memory ...................: 16302 MB physical, 48302 MB virtual
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - CPU ......................: GenuineIntel , 8 cores, 16 logical processors
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Developer mode enabled ...: yes
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Additional module paths ..: C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26489/QuantitativeReporting/lib/Slicer-4.8/qt-scripted-modules, C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26489/SlicerDevelopmentToolbox/lib/Slicer-4.8/qt-scripted-modules, C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26489/DCMQI/lib/Slicer-4.8/cli-modules
[DEBUG][Python] 20.11.2017 10:54:12 [Python] (C:\Program Files\Slicer 4.8.0\lib\Python\Lib\site-packages\git\cmd.py:719) - Popen(%s, cwd=%s, universal_newlines=%s, shell=%s)
[DEBUG][Python] 20.11.2017 10:54:12 [Python] (C:\Program Files\Slicer 4.8.0\lib\Python\Lib\site-packages\git\cmd.py:719) - Popen(%s, cwd=%s, universal_newlines=%s, shell=%s)
[DEBUG][Python] 20.11.2017 10:54:13 [Python] (C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 20.11.2017 10:54:13 [Python] (C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 20.11.2017 10:54:14 [Python] (C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 20.11.2017 10:54:11 [] (unknown:0) - Number of registered modules: 148
[CRITICAL][Stream] 20.11.2017 10:54:13 [] (unknown:0) - SystemError: D:\D\P\Slicer-480-package\Python-2.7.13\Objects\classobject.c:521: bad argument to internal function
[CRITICAL][Qt] 20.11.2017 10:54:13 [] (unknown:0) - qSlicerPythonCppAPI::instantiateClass  - [ "__init__" ] - Failed to instantiate scripted pythonqt class "__init__" 0x22fb8eb4160
[CRITICAL][Qt] 20.11.2017 10:54:13 [] (unknown:0) - Fail to instantiate module  "__init__"
[DEBUG][Qt] 20.11.2017 10:54:13 [] (unknown:0) - Number of instantiated modules: 147
[WARNING][Qt] 20.11.2017 10:54:13 [] (unknown:0) - When loading module  "DICOMTID1500Plugin" , the dependency "DICOMRWVMPlugin" failed to be loaded.
[DEBUG][Qt] 20.11.2017 10:54:14 [] (unknown:0) - Number of loaded modules: 146
[DEBUG][Qt] 20.11.2017 10:54:14 [] (unknown:0) - Switch to module:  "Welcome"
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -   File "C:/Program Files/Slicer 4.8.0/lib/Slicer-4.8/qt-scripted-modules/DICOM.py", line 84, in performPostModuleDiscoveryTasks
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -     DICOMLib.setDatabasePrecacheTags()
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -   File "C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 40, in setDatabasePrecacheTags
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -     plugin = slicer.modules.dicomPlugins[pluginClass]()
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -   File "C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26489/QuantitativeReporting/lib/Slicer-4.8/qt-scripted-modules/DICOMTID1500Plugin.py", line 25, in __init__
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) -     self.rwvmPlugin = slicer.modules.dicomPlugins["DICOMRWVMPlugin"]()
[CRITICAL][Stream] 20.11.2017 10:54:14 [] (unknown:0) - KeyError: 'DICOMRWVMPlugin'
[INFO][Stream] 20.11.2017 10:54:14 [] (unknown:0) - Loading Slicer RC file [C:/Users/msliv/.slicerrc.py]
[DEBUG][Qt] 20.11.2017 10:54:16 [] (unknown:0) - Switch to module:  "DICOM"
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:/Program Files/Slicer 4.8.0/lib/Slicer-4.8/qt-scripted-modules/DICOM.py", line 327, in setup
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     self.detailsPopup = self.getSavedDICOMDetailsWidgetType()()
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 996, in __init__
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     super(DICOMDetailsWindow, self).__init__(dicomBrowser, parent)
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 965, in __init__
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     DICOMDetailsBase.__init__(self, dicomBrowser)
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 100, in __init__
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     setDatabasePrecacheTags(self.dicomBrowser)
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:\Users\msliv\AppData\Roaming\NA-MIC\Extensions-26489\QuantitativeReporting\lib\Slicer-4.8\qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 40, in setDatabasePrecacheTags
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     plugin = slicer.modules.dicomPlugins[pluginClass]()
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26489/QuantitativeReporting/lib/Slicer-4.8/qt-scripted-modules/DICOMTID1500Plugin.py", line 25, in __init__
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     self.rwvmPlugin = slicer.modules.dicomPlugins["DICOMRWVMPlugin"]()
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) - KeyError: 'DICOMRWVMPlugin'
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:/Program Files/Slicer 4.8.0/lib/Slicer-4.8/qt-scripted-modules/DICOM.py", line 268, in enter
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     self.onOpenDetailsPopup()
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -   File "C:/Program Files/Slicer 4.8.0/lib/Slicer-4.8/qt-scripted-modules/DICOM.py", line 368, in onOpenDetailsPopup
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) -     if not isinstance(self.detailsPopup, self.getSavedDICOMDetailsWidgetType()):
[CRITICAL][Stream] 20.11.2017 10:54:16 [] (unknown:0) - AttributeError: DICOMWidget instance has no attribute 'detailsPopup'
```

**Comment by che85** [comment] 2017-11-20 16:10
That's interesting. How can that even be affected by DICOMPlugins?

**Comment by che85** [comment] 2017-11-20 16:22
I can reproduce this by removing the dependency to PETDICOMExtension, but I still don't understand how a DICOMPlugin can affect the whole DICOM widget since I don't work directly on it ...

**Comment by che85** [comment] 2017-11-20 16:35
I think i found an issue with the CMakeFile. Let me check on it

**Comment by che85** [comment] 2017-11-20 16:48
I am not sure if the following lines cause issues:

```
file(GLOB_RECURSE MODULE_PYTHON_SCRIPTS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
  *.py
)

file(GLOB_RECURSE MODULE_PYTHON_RESOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
  ${PROJECT_SOURCE_DIR}/${MODULE_NAME}/Resources/*
)

slicerMacroBuildScriptedModule(
  NAME ${MODULE_NAME}
  SCRIPTS ${MODULE_PYTHON_SCRIPTS}
  RESOURCES ${MODULE_PYTHON_RESOURCES}
)
```

Looking at the installed extension from the most recent nightly build, seems like there is something wrong with the added python files. In SliceTracker I have been doing the same in my CMakeLists.txt and it doesn't cause copying all those Slicer Python sources (see https://github.com/SlicerProstate/SliceTracker/blob/master/SliceTracker/CMakeLists.txt):

![image](https://user-images.githubusercontent.com/10195822/33030070-53127b20-cde8-11e7-9b18-ca3e929ab8ff.png)

@jcfr Maybe you know more?

**Comment by che85** [comment] 2017-11-20 16:51
I thought about added the MODULE_PYTHON_SCRIPTS manually, but I thought it might be easier to just add them automatically to make sure that no one forgets to add sources to the CMakeLists.

**Comment by lassoan** [comment] 2017-11-20 17:05
That's a good idea. In general, it's a better to specify build input files explicitly instead of globbing, for several reasons (make sure all the files that are expected and only those are used; make sure the project is rebuilt when files are added/removed, etc.).

**Comment by che85** [comment] 2017-11-20 17:19
Ok will do. But it's still strange that for SliceTracker [1] those Issues don't exist. 

[1] https://github.com/SlicerProstate/SliceTracker/blob/master/SliceTracker/CMakeLists.txt#L4-L6

**Comment by che85** [comment] 2017-11-20 17:31
I think instead of adding them explicitly, I will just change the lines to:

```
file(GLOB_RECURSE MODULE_PYTHON_SCRIPTS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
  ${PROJECT_SOURCE_DIR}/${MODULE_NAME}/*.py
)
```

I think that should fix the problem.

**Comment by che85** [comment] 2017-11-21 18:34
Seems like my last approach didn't work. I will check with SliceTracker, what's different there and might give it another try. Otherwise I will manually specify the sources.

**Comment by lassoan** [comment] 2017-11-21 18:38
Listing of source files explicitly is the proper solution - see https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil. As it is already broken, now it is a good time get rid of globbing.

**Comment by che85** [comment] 2017-11-22 15:58
The problem still exists although I added only specific python sources.

**Comment by che85** [comment] 2017-12-04 15:57
@lassoan @jcfr 
When installing QuantitativeReporting and looking into the qt-scripted-modules directory, it still seems that all Slicer python sources are copied into that directory. Instead of using the glob command I am defining specifically the QuantitativeReporting python sources to be added in the CMakeLists.txt [1]

I don't know what else I can do. Any ideas?

![image](https://user-images.githubusercontent.com/10195822/33561737-7b747484-d8e1-11e7-952f-f2d736b62b43.png)

[1] https://github.com/QIICR/QuantitativeReporting/blob/46212c297c8a02902b276777f23dfad9092cb0bb/QuantitativeReporting/CMakeLists.txt#L3-L13

**Comment by lassoan** [comment] 2017-12-04 16:28
Eventually, globbing has to be replaced by explicit listing of source files. As you have a problem with this part of the code, it is a good time to get rid of globbing now. If you have problems after switching to explicit file list, then let us know.

**Comment by fedorov** [comment] 2017-12-04 16:49
@lassoan if I understand correctly, Christian is already specifying the file names explicitly, see https://github.com/QIICR/QuantitativeReporting/issues/203#issuecomment-349005727.

**Comment by lassoan** [comment] 2017-12-04 16:54
Yes, .py file list is explicit now. In the referred CMakeLists.txt a few lines below the included snippet there is still a glob for resource files. Are you sure that this glob does not pull in all those files?

**Comment by che85** [comment] 2017-12-04 17:19
I don't know. I will just go ahead and specify the resources manually as well.

**Comment by lassoan** [comment] 2017-12-04 20:11
> When installing QuantitativeReporting and looking into the qt-scripted-modules directory, it still seems that all Slicer python sources are copied into that directory.

Copying of those extra files is caused by this call:

https://github.com/QIICR/QuantitativeReporting/blob/46212c297c8a02902b276777f23dfad9092cb0bb/Testing/CMakeLists.txt#L3-L8

I'm not sure why this happens, but if you follow patterns that are used in other modules then most probably you won't run into this issue.

**Comment by che85** [comment] 2017-12-04 20:30
@lassoan Are you sure? How can that even cause this issue? The source script file and a destination directory which is the slicer binary scripted modules directory are defined. I wouldn't expect it to be the other way around where the destination directory would act as a source ...

@jcfr Any ideas?

P.S. I just merged the PR and will take a look again tomorrow to see if the second `glob` maybe caused this issue.

**Comment by lassoan** [comment] 2017-12-04 20:33
Remove those lines and you'll see. Have you seen this macro used in any extension?

**Comment by jcfr** [comment] 2017-12-04 20:38
`ctkMacroCompilePythonScript` was used before we introduce `slicerMacroBuildScriptedModule`, `slicer_add_python_unittest` and `slicer_add_python_unittest`

**Comment by che85** [comment] 2017-12-04 21:52
@jcfr Are `slicer_add_python_unittest` and `slicer_add_python_test` supposed to copy the test source file as well? I cannot see the QuantitativeReportingTests.py in my build directory.

**Comment by jcfr** [comment] 2017-12-04 21:59
>  supposed to copy the test source file as well? 

No. they only add corresponding tests.

If you want to package and distribute the test scripts, you could list them with `slicerMacroBuildScriptedModule`

**Closed** 2017-12-05 01:00 UTC
Labels: bug, high priority

**Comment by che85** [comment] 2017-12-05 21:43
No idea what's going on here http://slicer.cdash.org/viewBuildError.php?buildid=1146160

Those errors didn't occur before and I didn't change any of that CMakeLists code

**Comment by lassoan** [comment] 2017-12-05 22:01
Is packaging (building PACKAGE target) successful on your computer?

**Comment by che85** [comment] 2017-12-06 20:31
For any reason it's back in today's nightly build.
