### ISSUE TITLE
Invalid terminology information in tooltip and Slicer crash using segment descriptor file context

### ISSUE THREAD

**Issue by che85** [QIICR/QuantitativeReporting#135] opened 2017-01-24 22:59 UTC
Terminology seems not to work properly anymore when LoadTerminologyFromSegmentDescriptorFile/LoadAnatomicContextFromSegmentDescriptorFile are used. 

Hovering over a segment within the integrated Segment Editor displays "invalid terminology information"

![image](https://cloud.githubusercontent.com/assets/10195822/22269990/be74ce1e-e25b-11e6-9efb-bb84d1cca89a.png)

Also, when creating new measurements and selecting the context which has been loaded from the segment descriptor file, Slicer crashes. [1]

This is not related to the changes I made in https://github.com/QIICR/QuantitativeReporting/issues/132

My assumption is, that this is related to the changes made using rapidjson instead of jsoncpp.

@cpinter , @lassoan Any ideas?

[1] https://gist.github.com/che85/4d0a772ac5adc03958333c2a16f8f3a1

**Comment by che85** [comment] 2017-01-25 16:31
@fedorov Any thoughts on this? It's essential for the paper...

**Comment by fedorov** [comment] 2017-01-25 16:34
I was hoping @cpinter and @lassoan will respond. Considering no response, can you investigate a bit deeper?

**Comment by che85** [comment] 2017-01-25 16:39
I tested on nightly build 01/06/2017 with using the master dcmqi and master QuantitativeReporting. This worked for me which brings me to the conclusion, that it must be the integration of rapidjson

**Comment by lassoan** [comment] 2017-01-25 16:40
I've just got to this now. Quite likely regression due to rapidjson. I'm investigating.

**Comment by lassoan** [comment] 2017-01-25 16:45
I need step-by-step instructions to reproduce the problem (simply browsing/changing terminologies in Segment Editor works fine)

**Comment by che85** [comment] 2017-01-25 16:50
1. load a structured report from the DICOM browser
2. open Quantitative Reporting
3. select table
4. hover over color icon and check if it works

**Comment by che85** [comment] 2017-01-25 16:52
Dataset that I used is QIN-HEADNECK-01-0139 from http://slicer.kitware.com/midas3/folder/3771

**Comment by fedorov** [comment] 2017-01-25 16:53
> load a structured report from the DICOM browser

= in the DICOM browser select a series with modality SR from that study that Christian mentioned above

**Comment by lassoan** [comment] 2017-01-25 16:55
ok, thanks!

**Comment by cpinter** [comment] 2017-01-25 18:03
I also just got the notification. I'll look at the issue with the data you linked.

**Comment by fedorov** [comment] 2017-01-25 18:09
Thanks guys!

**Comment by cpinter** [comment] 2017-01-25 18:13
Although the email header says 6PM yesterday, I'm pretty sure I just got it. Not sure why this is.
So in the future if something is urgent, probably sending a direct email too is a good idea, just in case.

**Comment by cpinter** [comment] 2017-01-25 21:03
Sorry for the delay, I needed to rebuild parts of Slicer after updating. I also updated and built DCMQI and QuantitativeReporting.

When I load the SR series, I get this error
`Traceback (most recent call last):
  File "C:/d/S4R/Slicer-build/lib/Slicer-4.7/qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 790, in loadCheckedLoadables
    self.proceedWithReferencedLoadablesSelection()
  File "C:/d/S4R/Slicer-build/lib/Slicer-4.7/qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 840, in proceedWithReferencedLoadablesSelection
    if not plugin.load(loadable):
  File "c:/d/_Other/QuantitativeReporting_R/lib/Slicer-4.7/qt-scripted-modules/DICOMTID1500Plugin.py", line 121, in load
    rwvmPlugin = slicer.modules.dicomPlugins["DICOMRWVMPlugin"]()
KeyError: 'DICOMRWVMPlugin'`

Any ideas what to do?

**Comment by fedorov** [comment] 2017-01-25 21:09
Csaba, we introduced a new dependency, which would be resolved if you installed via ExtensionManager.

You will need to build and add to the paths this extension: https://github.com/QIICR/Slicer-PETDICOMExtension

**Comment by cpinter** [comment] 2017-01-25 21:14
Good to know, thanks!

Is it intentional that the name of this extension has "Slicer-" prefix and "Extension" postfix, while the others have neither? (QuantitativeReporting, LongitudinalPETCT, etc)

**Comment by cpinter** [comment] 2017-01-25 21:21
After downloading and building the other extension I got past the previous error.
However I get another one, and I'm pretty sure it's not related to the original issue:

`Traceback (most recent call last):
  File "C:/d/S4R/Slicer-build/lib/Slicer-4.7/qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 790, in loadCheckedLoadables
    self.proceedWithReferencedLoadablesSelection()
  File "C:/d/S4R/Slicer-build/lib/Slicer-4.7/qt-scripted-modules\DICOMLib\DICOMWidgets.py", line 840, in proceedWithReferencedLoadablesSelection
    if not plugin.load(loadable):
  File "c:/d/_Other/QuantitativeReporting_R/lib/Slicer-4.7/qt-scripted-modules/DICOMTID1500Plugin.py", line 203, in load
    segmentationNodeID = segmentationNodes.GetItemAsObject(segmentationNodes.GetNumberOfItems()-1).GetID()
AttributeError: 'NoneType' object has no attribute 'GetID'`

**Comment by lassoan** [comment] 2017-01-25 21:22
I've installed PETDICOMExtension and the issue is the same.

**Comment by che85** [comment] 2017-01-25 21:26
@cpinter That probably means, that the Segmentation is not properly loaded into Slicer. Are you using the most recent version of QuantitativeReporting and dcmqi?

**Comment by cpinter** [comment] 2017-01-25 21:26
Yes

**Comment by che85** [comment] 2017-01-25 21:27
Other than that, there should be any error output in the log... or the segmentation itself is missing in the SlicerDICOMDatabase

**Comment by fedorov** [comment] 2017-01-25 21:27
@che85 could this be related to https://github.com/QIICR/dcmqi/pull/173? I have not tested the latest one, but it worked for me in earlier nightlies.

**Comment by fedorov** [comment] 2017-01-25 21:28
> Is it intentional that the name of this extension has "Slicer-" prefix and "Extension" postfix, while the others have neither? (QuantitativeReporting, LongitudinalPETCT, etc)

@cpinter that extension was developed by the Iowa team, and they follow their own naming conventions. I agree, I don't see a need for those. Maybe @chribaue can comment on this.

**Comment by che85** [comment] 2017-01-25 21:29
@fedorov no that cannot be related since QIICR/dcmqi#173 is only about the webapps

**Comment by cpinter** [comment] 2017-01-25 21:30
I imported the whole folder into the database, so this should not be the problem
![image](https://cloud.githubusercontent.com/assets/1325980/22309935/67596ade-e31b-11e6-9fe9-864b53b2e965.png)

I get this in the log also:
"SEG2NRRD did not complete successfully, unable to load DICOM Segmentation"
"RWVM is referenced from SR, but is not found in the DICOM database!"
The second one makes no sense, as it is in the DB.

**Comment by fedorov** [comment] 2017-01-25 21:31
> The second one makes no sense, as it is in the DB.

If it is the same one that is referenced from SEG ... I will download the nightly and test from scratch now. Building is a slower option, since my slicer build is quite old.

**Comment by fedorov** [comment] 2017-01-25 21:33
@che85 sorry - I meant this one https://github.com/QIICR/dcmqi/pull/170. Maybe in the process of changing the attribute names something was broken?

**Comment by che85** [comment] 2017-01-25 21:34
@fedorov No I am pretty sure that it doesn't have to do with that since I tested the new dcmqi and Quantitative Reporting with an older nightly of Slicer from 01/06/2017 before integration of rapidjson

**Comment by che85** [comment] 2017-01-25 21:39
@cpinter @fedorov @lassoan I am getting the same error with the latest nightly. I will look into the error messages

```
Traceback (most recent call last):
  File "/Applications/Slicer 2.app/Contents/lib/Slicer-4.7/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 790, in loadCheckedLoadables
    self.proceedWithReferencedLoadablesSelection()
  File "/Applications/Slicer 2.app/Contents/lib/Slicer-4.7/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 840, in proceedWithReferencedLoadablesSelection
    if not plugin.load(loadable):
  File "/Applications/Slicer 2.app/Contents/Extensions-25669/QuantitativeReporting/lib/Slicer-4.7/qt-scripted-modules/DICOMTID1500Plugin.py", line 203, in load
    segmentationNodeID = segmentationNodes.GetItemAsObject(segmentationNodes.GetNumberOfItems()-1).GetID()
AttributeError: 'NoneType' object has no attribute 'GetID'
```

**Comment by che85** [comment] 2017-01-25 21:42
OK the above bug is related to a dcmqi issue invented by me when I implemented supporting more ITK output types:
```
Convert DICOM SEG into ITK image standard error:

PARSE ERROR: Argument: -t (--outputType)
             Value 'nrrd' does not meet constraint: mhd|mha|nii|nifti|hdr|img

Brief USAGE: 

For complete USAGE and HELP type: 
   /Applications/Slicer 2.app/Contents/Extensions-25669/DCMQI/lib/Slicer-4.7/cli-modules/segimage2itkimage --help




Convert DICOM SEG into ITK image completed with errors
```

**Comment by cpinter** [comment] 2017-01-25 22:04
Great, thanks! I hope it's easy to fix. After that I'll keep going on this one.

**Comment by fedorov** [comment] 2017-01-25 22:07
Nope, not so easy - there is something else. We are debugging it.

**Comment by ejulrich** [comment] 2017-01-25 22:33
> > Is it intentional that the name of this extension has "Slicer-" prefix and "Extension" postfix, while the others have neither? (QuantitativeReporting, LongitudinalPETCT, etc)

> @cpinter that extension was developed by the Iowa team, and they follow their own naming conventions. I agree, I don't see a need for those. Maybe @chribaue can comment on this.

@fedorov I followed the naming convention for extension repositories outlined in an [old Slicer wiki page](https://www.slicer.org/w/index.php?title=Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions&oldid=36727 "old Slicer wiki page"). The naming convention suggests having the "Slicer-" prefix. The [current page](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions "current page") also suggests using the prefix while creating an extension with the wizard. It looks like this convention is not often followed. As for the "Extension" postfix, that was just a style choice.

**Comment by cpinter** [comment] 2017-01-25 23:15
@ejulrich Thanks for the explanation! For some reason I assumed this extension also comes from SPL, so I was just surprised by the naming.

**Comment by fedorov** [comment] 2017-01-25 23:21
@cpinter people outside SPL actually read the guidelines about naming conventions! :)

@ejulrich thanks for the clarification, I suspected there must be a reason!

**Comment by fedorov** [comment] 2017-01-25 23:32
@cpinter can you update dcmqi and QuantitativeReporting to the latest master and try again?

**Comment by cpinter** [comment] 2017-01-26 00:41
I updated, and now loading suceeds. Thanks!

The crash happens at this line:
`segmentationCodes = terminologyRoot["SegmentationCodes"];`
It's not trivial why, I keep investigating.

**Comment by cpinter** [comment] 2017-01-26 00:47
It's unrelated but I discovered that the tag AnatomicRegionCodeSequence has changed since the implementation of this function to AnatomicRegionSequence, so it wouldn't have worked for sure if I don't notice this now. Changes in the file schema would be important to follow in the code.

**Comment by che85** [comment] 2017-01-26 00:52
@cpinter both changed https://github.com/QIICR/QuantitativeReporting/pull/133/files

**Comment by che85** [comment] 2017-01-26 00:56
@cpinter also see here https://github.com/QIICR/dcmqi/pull/170/files

**Comment by cpinter** [comment] 2017-01-26 01:03
I think it would be better to act proactively to make sure these changes are propagated throughout the code, as the alternative is a regression.

**Comment by fedorov** [comment] 2017-01-26 01:42
Csaba, indeed. We are struggling with propagating this kind of changes in other places as well. We should have thought about it. But error reporting could be improved too!

**Comment by cpinter** [comment] 2017-01-26 06:58
Unfortunately rapidjson differs from jsoncpp a great deal when it's about creating a document not querying one (which happens when converting from the descriptor json to the terminology dictionary json). I made some progress but not quite there yet. I'll let you know when I'm done with the fix.

**Comment by cpinter** [comment] 2017-01-27 00:03
Commit https://github.com/Slicer/Slicer/commit/67a87bc191baa97be9949677cae0e60e9f118724 fixes loading the segmentation descriptor files into terminologies and anatomic contexts.

Unfortunately when I tried it in release mode the terminology was empty (the anatomic context was correct). I will check why this is.

**Comment by fedorov** [comment] 2017-01-27 02:55
That's a lot of code, but looks like your goal is to make it more bullet proof in case there are missing items in JSON. Sorry, I didn't realize this would be so much work.

**Comment by cpinter** [comment] 2017-01-27 03:06
My goal was merely to make it work. As I said RapidJson's way is very different when it comes to creating objects, so the ugly syntax and the extra checks are due to the stricter nature of the library.

I'm still not sure why the regions are loaded fine while the terminology is not. It's only in release mode, as in debug both work.

**Comment by lassoan** [comment] 2017-01-27 04:58
clang build errors/warnings may give a hint about what's wrong:

Build command: /Users/kitware/Dashboards/Support/CMake-3.5.0-rc3.app/Contents/bin/cmake --build . --config "Release" -- -i -j9 -l8 
Start Time: 2017-01-27T04:10:22 UTC 
End Time: 2017-01-27T04:54:55 UTC 

Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx 
/Users/kitware/Dashboards/Nightly/Slicer-0/Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx:779:12: warning: reference to stack memory associated with local variable 'terminologyRoot' returned [-Wreturn-stack-address]
    return terminologyRoot;
           ^~~~~~~~~~~~~~~
/Users/kitware/Dashboards/Nightly/Slicer-0/Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx:911:12: warning: reference to stack memory associated with local variable 'anatomicContextRoot' returned [-Wreturn-stack-address]
    return anatomicContextRoot;
           ^~~~~~~~~~~~~~~~~~~
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0/Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx:45:
/Users/kitware/Dashboards/Nightly/Slicer-0-build/RapidJSON/include/rapidjson/document.h:71:8: error: binding of reference to type 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' to a value of type 'const GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' drops qualifiers
struct GenericMember { 
       ^~~~~~~~~~~~~
/Users/kitware/Dashboards/Nightly/Slicer-0-build/RapidJSON/include/rapidjson/document.h:1365:13: note: in instantiation of member function 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::RemoveMember' requested here
            RemoveMember(m);
            ^
/Users/kitware/Dashboards/Nightly/Slicer-0-build/RapidJSON/include/rapidjson/document.h:1354:16: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::RemoveMember<rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' requested here
        return RemoveMember(n);
               ^
/Users/kitware/Dashboards/Nightly/Slicer-0/Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.cxx:730:14: note: in instantiation of member function 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::RemoveMember' requested here
        type.RemoveMember("Modifier");
             ^
/Users/kitware/Dashboards/Nightly/Slicer-0-build/RapidJSON/include/rapidjson/document.h:755:43: note: passing argument to parameter 'rhs' here
    GenericValue& operator=(GenericValue& rhs) RAPIDJSON_NOEXCEPT {
                                          ^
/Users/kitware/Dashboards/Nightly/Slicer-0-build/RapidJSON/include/rapidjson/document.h:1388:16: note: implicit default copy assignment operator for 'rapidjson::GenericMember<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' first required here
            *m = *last; // Move the last one to this place
               ^
2 warnings and 1 error generated.

**Comment by cpinter** [comment] 2017-01-27 16:01
I just made another commit that fixes the release issues https://github.com/Slicer/Slicer/commit/552a37c04f97434eecb94ca39c5cf8282053925a.
I still need to fix minor things (right now the same descriptor file cannot be loaded twice because then the whole context becomes empty), but decided to make the commit to see if it fixes the Mac build errors. I cannot seem to build Slicer on my Mac any more, something must have changed.
@fedorov Could you please try to build it on Mac? If there is still a build error we need to be able to fix it somehow.

**Comment by fedorov** [comment] 2017-01-27 16:05
👍  thanks - will start the build. Do you want Debug or Release?

**Comment by cpinter** [comment] 2017-01-27 16:08
I think Release would be better because then you could test the previous release issue as well. Thank you!

**Comment by cpinter** [comment] 2017-01-27 16:19
A piece of good news: QuantitativeReporting works with the latest commit, at least on Windows:
![image](https://cloud.githubusercontent.com/assets/1325980/22378116/737dfd62-e482-11e6-8c03-fb53bccc63eb.png)
Sorry that the fix took so long! RapidJson is very different from JsonCpp!

**Comment by fedorov** [comment] 2017-01-27 17:03
macOS + Release = SimpleITK build error

![image](https://cloud.githubusercontent.com/assets/313942/22379747/9789f19c-e488-11e6-9696-3257b10c77dc.png)

**Comment by fedorov** [comment] 2017-01-27 17:03
I thought this used to work ... let me think what I can turn off/change ...

**Comment by cpinter** [comment] 2017-01-27 17:26
Strange. Unfortunately the CircleCI check also doesn't work any more (the last 15 or so checks failed the same way although all of them except my commit yesterday should have passed). Maybe we can ask Steve or someone to try to build it as well. I understand it's really urgent to make this work, and Christian only has Mac.

FYI I committed another small fix, it should be good now. There is only one very minor issue, namely that when entering QuantitativeReporting after loading the SR I get this warning many times:
`Generic Warning: In C:\d\Slicer4\Modules\Loadable\Terminologies\Logic\vtkSlicerTerminologiesModuleLogic.cxx, line 434
PopulateTerminologyTypeFromJson: Unsupported data type for recommendedDisplayRGBValue`
@che85 Do you remember seeing these warnings with the last version that worked, or do you think it's new? I cannot reproduce it without the QuantitativeReporting stuff, and SimpleITK doesn't build in debug on Windows, and in Release there is only so much I can do. Apart from this warning message it seems to work well now.

**Comment by fedorov** [comment] 2017-01-27 17:37
I have no idea what is going on with my build. I checked the manual, and there are no special provisions re SimpleITK on Mac. @che85 can you run a build on your system? Maybe it is because my OS is couple of generations old. Although, I know my build was working recently.

**Comment by cpinter** [comment] 2017-01-27 17:42
I got similar ITK-related errors about but when building CTK. I also skipped OS updates, and I stopped being able to build Slicer a few months ago. I'm updating now to whatever animal or national park is the latest, then try from scratch. I won't be able to finish today for sure though.

**Comment by fedorov** [comment] 2017-01-27 17:44
I will update, but not before Feb 1 - too much risk of breaking things I will need for the paper!

**Comment by fedorov** [comment] 2017-01-27 17:47
Ah, I think I might have found it!

I think I actually did have this issue before. I will be trying this suggestion from Brad that worked last time:

> There is the SimpleITK CMake options “SITK_EXPLICIT_INSTANTIATION”which could be set to OFF to solve this problem on your platform. Or maybe if you compile with SimpleITK static libraries it would not be an issue too.

Maybe not too late for you!

**Comment by cpinter** [comment] 2017-01-27 17:49
It is :( However a build error should be quite easy to fix once you can reproduce. Although I hope the error is gone, as they seemed to be related to two warnings which I fixed since then.

**Comment by che85** [comment] 2017-01-27 17:50
@cpinter I cannot recall if I have ever seen this error message.

**Comment by fedorov** [comment] 2017-01-27 17:51
@cpinter to make you feel better - that trick did not help!

**Comment by cpinter** [comment] 2017-01-27 17:51
@che85 Thanks! I'm trying to fix it, but nevertheless, if the Mac build is OK then it will work now.

**Comment by lassoan** [comment] 2017-01-27 17:56
It would be useful to limit SimpleITK dependency, as it's a huge component and the inability to debug makes troubleshooting almost impossible on Windows. Of course SimpleITK can be still used, but try to implement modules so that only those features are not available that actually require SimpleITK.

**Comment by cpinter** [comment] 2017-01-27 18:10
@pieper If you can easily update and build Slicer on your Mac would you please try that? Thank you!

**Comment by che85** [comment] 2017-01-27 18:13
I am also going to build Slicer from scratch now on my Mac.

**Comment by che85** [comment] 2017-01-27 20:15
I was able to build Slicer without problems from Slicer/Slicer@707ee807afa069efb9732aad8646a41e5980eadc

**Comment by pieper** [comment] 2017-01-27 23:59
I've started a fresh mac build of the current master.

**Comment by pieper** [comment] 2017-01-28 00:50
My fresh (debug) build seems to work fine.  Is there something else to test?

[image: Inline image 1]

**Comment by cpinter** [comment] 2017-01-28 00:58
That's great news, thanks!

@che85 could also build, so he can test the rest with the proper dataset and extensions.
I was worried it didn't build because the error message didn't make much sense to me, and was not sure if my commit actually fixed it.

**Comment by che85** [comment] 2017-01-28 02:33
@cpinter no I cannot test it with my Slicer build since Slicer is not starting properly on my Mac OS Sierra. Will have to wait for the next nightly build.

**Comment by cpinter** [comment] 2017-01-28 03:50
@che85 Do you know why it doesn't start? This is not what I'd call built without problems.

**Comment by che85** [comment] 2017-01-28 03:54
@cpinter Slicer built 100% without errors. My startup problems already existed months ago...

**Comment by che85** [comment] 2017-01-28 06:40
Seems like the nightly failed on the build system for Mac: http://slicer.cdash.org/viewBuildError.php?buildid=962482

Interesting that neither @pieper nor my build failed

**Comment by lassoan** [comment] 2017-01-28 06:49
It seems to be a ConstMemberIterator / MemberIterator mismatch.

Solution is probably to replace RemoveMember by EraseMember as suggested here: https://github.com/miloyip/rapidjson/issues/721

@cpinter Can you give this potential solution a try? (if you cannot test it yourself then just change it and wait for the next nightly)

**Comment by cpinter** [comment] 2017-01-28 14:23
I replaced all RemoveMember calls to EraseMember, and it seems to work OK.
I cannot test Mac build (and apparently Christian and Steve cannot either as it succeeded for them before), so we'll see how the nightly goes.

**Comment by fedorov** [comment] 2017-01-28 17:30
I built Slicer with SimpleITK disabled, in Release mode. Loading works fine, and I see segmentations overlayed. I cannot access QuantitativeReporting UI, since it has a dependency on SimpleITK, but when I try to switch to SegmentEditor, I get a crash.

I will now build in Debug to see if I can get any more info on the crash.

**Comment by fedorov** [comment] 2017-01-28 17:54
Ok, I am super confused now - now it is working! It was crashing repeatedly, then I discovered it was actually build in debug mode (I guess the flag got reset as I was rebuilding), so I ran it in the debugger, it didn't crash, and now I cannot reproduce the problem. Hope I was just messing something up earlier - fingers crossed for tomorrow nightly!

**Comment by cpinter** [comment] 2017-01-28 17:59
Thanks for the news, Andrey! We're actually late from a party now, so I'll then stop trying to reproduce and will get back to it in the evening. I hope it's not broken!

**Comment by fedorov** [comment] 2017-01-28 18:06
Csaba, definitely - it makes a lot of sense to wait until tomorrow. Thanks for your efforts!

**Comment by cpinter** [comment] 2017-01-29 14:17
Mac build was successful on the factory, so that's good.
I tried reproducing the crash with Segment Editor, but I was unsuccessful.
Let me know if there are further issues.

**Comment by fedorov** [comment] 2017-01-29 22:11
Confirmed, looks good - thanks!!

**Closed by fedorov** 2017-01-29 22:11 UTC
Labels: bug, high priority
