### ISSUE TITLE
Slicer crash when doing creating segmentations and quitting Slicer afterwards

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#145] opened 2017-02-23 21:37 UTC
Same on Windows machines as far as I could test it.

**Comment by cpinter** [comment] 2017-02-23 21:45
I tested it right now on rev25717, and I had no problems after exiting Slicer. Here's what I did:
* Load MRHead
* Go to Segment Editor
* Add segment
* Use Paint effect to paint something
* Exited Slicer
Nothing happened, it seemed to be a clean exit. The only message on the terminal was that "vtkDebugLeaks has found no leaks"

**Comment by fedorov** [comment] 2017-02-23 21:48
to clarify, the report above was from @che85 - I didn't do testing to confirm this. A bit misleading with converting notes I copy-pasted from email into an issue!

**Comment by che85** [comment] 2017-02-23 21:50
@cpinter could you try steps 1. to 4. again and then push "Restart Slicer"? That's when I get the errors.

**Comment by cpinter** [comment] 2017-02-23 21:52
By clicking restart Slicer it did crash, but the new Slicer appeared alright.
Good, now we know how to reproduce. I hope the debugger will show a usable call stack.

**Comment by che85** [comment] 2017-02-23 21:54
Same happens on ubuntu:

```
void qSlicerSubjectHierarchySegmentationsPlugin::onSegmentModified(vtkObject*, void*) : Unable to find subject hierarchy node for segmentation node  Segmentation  so per-segment subject hierarchy node cannot be created 
Switch to module:  "" 
error: [/home/parallels/Documents/Slicer-4.7.0-2017-02-18-linux-amd64/./bin/SlicerApp-real] exit abnormally - Report the problem.
```

**Comment by cpinter** [comment] 2017-02-23 21:58
I was able to debug. The problem is that by the time the module exit function is called, the views are already dstroyed, and when trying to remove actors, it crashes. I find it strange that restart and simple exit works differently. I'll try to do a check before removing those actors using the layout manager.

**Comment by cpinter** [comment] 2017-02-23 22:34
Fixed. Please test, thanks!

**Comment by che85** [comment] 2017-03-01 20:44
Tested and works for me fine. Closing this issue.

**Closed by che85** 2017-03-01 20:44 UTC
Labels: bug
